#!/usr/bin/env bash
#SBATCH --job-name=melano_merge
#SBATCH --account=tlasisi1
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=6:00:00
#SBATCH --output=/nfs/turbo/lsa-tlasisi1/tlasisi/melanosome-constraints/logs/merge_%A_%a.out
#SBATCH --error=/nfs/turbo/lsa-tlasisi1/tlasisi/melanosome-constraints/logs/merge_%A_%a.err
#SBATCH --array=1-22

# 05_merge_filter_vcfs.sh
#
# Merges the lifted SGDP Melanesian VCF with the gnomAD HGDP+1KGP VCF
# (both now hg38), then applies population and variant filters.
#
# Output per chromosome (in vcf/filtered/):
#   melano_study.chr{N}.vcf.gz  — analysis-ready, all populations
#
# Plus per-population subsets (needed for π and PBS):
#   african.chr{N}.vcf.gz
#   melanesian.chr{N}.vcf.gz
#   eastasian.chr{N}.vcf.gz
#   southasian.chr{N}.vcf.gz
#
# Submit after 04_liftover_sgdp.sh completes:
#   sbatch 05_merge_filter_vcfs.sh

set -euo pipefail

module load bcftools htslib

BASE=/nfs/turbo/lsa-tlasisi1/tlasisi/melanosome-constraints
RAW="${BASE}/vcf/raw"
LIFTED="${BASE}/vcf/lifted"
FILTERED="${BASE}/vcf/filtered"
DATA="${BASE}/data"
CHR=${SLURM_ARRAY_TASK_ID}

mkdir -p "${FILTERED}"

# Sample list files (generated by 03_make_sample_lists.py)
ALL_KEEP="${DATA}/samples_all_keep.txt"
AFRICAN="${DATA}/samples_african.txt"
MELANESIAN_HGDP="${DATA}/samples_melanesian_hgdp.txt"
MELANESIAN_SGDP="${DATA}/samples_melanesian_sgdp.txt"
EAST_ASIAN="${DATA}/samples_eastasian.txt"
SOUTH_ASIAN="${DATA}/samples_southasian.txt"

GNOMAD_VCF="${RAW}/hgdp_1kgp.chr${CHR}.vcf.gz"
SGDP_VCF="${LIFTED}/sgdp_melanesian.chr${CHR}.hg38.vcf.gz"

# ─── Step 1: Merge gnomAD HGDP+1KGP + lifted SGDP ───────────────────────────
# If SGDP file exists, merge; otherwise just use gnomAD alone.
MERGED="${FILTERED}/merged.chr${CHR}.vcf.gz"

if [[ -f "${SGDP_VCF}" ]]; then
    echo "[$(date)] Merging gnomAD + SGDP for chr${CHR}..."
    bcftools merge \
        --merge snps \
        --output-type z \
        --threads 4 \
        --output "${MERGED}" \
        "${GNOMAD_VCF}" \
        "${SGDP_VCF}"
else
    echo "[$(date)] No SGDP VCF — using gnomAD only for chr${CHR}."
    cp "${GNOMAD_VCF}" "${MERGED}"
fi
tabix -p vcf "${MERGED}"

# ─── Step 2: Keep only our study samples, filter variants ─────────────────────
# Filters applied:
#   --samples-file   : keep only study samples (our population lists)
#   --min-ac 1       : drop monomorphic sites in the kept samples
#   --types snps     : SNPs only (no indels, no MNPs)
#   -m2 -M2          : biallelic sites only
#   -e 'F_MISSING > 0.1' : drop sites missing in >10% of samples
echo "[$(date)] Filtering chr${CHR}..."
STUDY_VCF="${FILTERED}/melano_study.chr${CHR}.vcf.gz"

bcftools view \
    --samples-file "${ALL_KEEP}" \
    --force-samples \
    --min-ac 1 \
    --types snps \
    -m2 -M2 \
    --output-type u \
    "${MERGED}" | \
bcftools filter \
    --exclude 'F_MISSING > 0.1' \
    --output-type z \
    --output "${STUDY_VCF}"

tabix -p vcf "${STUDY_VCF}"

N_VARS=$(bcftools view -H "${STUDY_VCF}" | wc -l)
N_SAMPS=$(bcftools query -l "${STUDY_VCF}" | wc -l)
echo "[$(date)] chr${CHR}: ${N_VARS} variants, ${N_SAMPS} samples after filtering."

# ─── Step 3: Write per-population subsets ────────────────────────────────────
# These are the inputs for π and PBS computations.
declare -A POP_FILES=(
    ["african"]="${AFRICAN}"
    ["melanesian"]="${MELANESIAN_HGDP}"   # HGDP; SGDP added below
    ["eastasian"]="${EAST_ASIAN}"
    ["southasian"]="${SOUTH_ASIAN}"
)

for POP in "${!POP_FILES[@]}"; do
    SAMPLE_FILE="${POP_FILES[$POP]}"
    OUT="${FILTERED}/${POP}.chr${CHR}.vcf.gz"

    # For Melanesian, merge HGDP + SGDP sample lists
    if [[ "${POP}" == "melanesian" && -f "${MELANESIAN_SGDP}" ]]; then
        COMBINED_MELAN=$(mktemp)
        cat "${MELANESIAN_HGDP}" "${MELANESIAN_SGDP}" > "${COMBINED_MELAN}"
        SAMPLE_FILE="${COMBINED_MELAN}"
    fi

    bcftools view \
        --samples-file "${SAMPLE_FILE}" \
        --force-samples \
        --min-ac 1 \
        --output-type z \
        --output "${OUT}" \
        "${STUDY_VCF}"

    tabix -p vcf "${OUT}"
    N=$(bcftools view -H "${OUT}" | wc -l)
    N_S=$(bcftools query -l "${OUT}" | wc -l)
    echo "  ${POP}: ${N} variants, ${N_S} samples → ${OUT}"

    [[ "${POP}" == "melanesian" && -f "${MELANESIAN_SGDP}" ]] && rm -f "${COMBINED_MELAN}"
done

# Clean up merged intermediate
rm -f "${MERGED}" "${MERGED}.tbi"

echo "[$(date)] chr${CHR} complete."
